name: epg update

on:
  schedule:
    - cron: "10 4,15,16,22 * * *"    # 设置定时执行，例如每天零点执行
  workflow_dispatch:  # 允许手动执行
  
jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        
      - name: Check git status
        run: git status
        
      - name: summary epg
        run: |
          wget https://raw.githubusercontent.com/sparkssssssssss/epg/main/pp.xml.gz -O "epg-"$(date -d "8 hours" "+%m%d")".xml.gz"
          rm -f epg.xml "epg-"$(date -d "8 hours" "+%m%d")".xml" "epg-"$(date -d "10 days ago" "+%m%d")".xml"
          gunzip "epg-"$(date -d "8 hours" "+%m%d")".xml.gz"
          sed -n '1,2p' "epg-"$(date -d "8 hours" "+%m%d")".xml" >> epg.xml 
          for i in {8..1}; do
            sed '1,2d' "epg-"$(date -d "$i days ago +8 hours" "+%m%d")".xml" | sed '$d' >> epg.xml
            echo "epg-"$(date -d "$i days ago +8 hours" "+%m%d")".xml"："汇总完成" 
          done
          sed '1,2d' "epg-"$(date -d "8 hours" "+%m%d")".xml" >> epg.xml  
          gzip -c epg.xml > epg.xml.gz

          #更新stream-link的epg
          wget http://content.stream-link.org/epg/guide.xml -O guide.xml
          id_mapping_file="./channel.txt"
          xml_file="./guide.xml"
          # 逐行读取 id 对应名单文件，并更新 XML 文件中对应的频道名称
          while IFS=',' read -r id name; do
              # 使用 sed 命令替换 XML 文件中的频道名称
              sed -i "s/<channel id=\"$id\"><display-name>[^<]*<\/display-name>/<channel id=\"$id\"><display-name>$name<\/display-name>/g" "$xml_file"
          done < "$id_mapping_file"
          echo "XML 文件已更新"
            
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git status
          git add .
          git status
          git commit -m "Update epg-$(date -d "8 hours" "+%m%d").xml，epg.xml，epg.xml.gz，guide.xml"
          git push origin main
