name: epg update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 4,15,16,22 * * *"    # 设置定时执行，例如每天零点执行
  workflow_dispatch:  # 允许手动执行
  
jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: summary epg
        run: |
          wget https://epg.112114.xyz/pp.xml.gz -O "epg-"$(date -d "8 hours" "+%m%d")".xml.gz"
          rm -f epg.xml "epg-"$(date -d "8 hours" "+%m%d")".xml" "epg-"$(date -d "10 days ago" "+%m%d")".xml"
          gunzip "epg-"$(date -d "8 hours" "+%m%d")".xml.gz"
          sed -n '1,2p' "epg-"$(date -d "8 hours" "+%m%d")".xml" >> epg.xml 
          for i in {8..1}; do
          sed '1,2d' "epg-"$(date -d "$i days ago" "+%m%d")".xml" | sed '$d' >> epg.xml
          done
          sed '1,2d' "epg-"$(date -d "8 hours" "+%m%d")".xml" >> epg.xml  
          gzip -c epg.xml > epg.xml.gz
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add "epg-"$(date -d "8 hours" "+%m%d")".xml"
          git commit -m "Update epg-$(date -d "8 hours" "+%m%d").xml"          
          git add epg.xml
          git commit -m "Update epg.xml"
          git add epg.xml.gz
          git commit -m "Update epg.xml.gz"
          git push origin main
