name: update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          wget https://epg.112114.xyz/pp.xml.gz -O "epg-"$(date -d "8 hours" "+%m%d")".xml.gz"
          rm epg.xml "epg-"$(date -d "8 hours" "+%m%d")".xml" "epg-"$(date -d "8 days ago" "+%m%d")".xml"
          gunzip "epg-"$(date -d "8 hours" "+%m%d")".xml.gz"
          sed -n '1,2p' "epg-"$(date -d "8 hours" "+%m%d")".xml" >> epg.xml 
          for i in {9..1}; do
          sed '1,2d' "epg-"$(date -d "$i days ago" "+%m%d")".xml" | sed '$d' >> epg.xml
          done
          sed '1,2d' "epg-"$(date -d "8 hours" "+%m%d")".xml" >> epg.xml  
          gzip -c epg.xml > epg.xml.gz
          git config --local user.email "1062253873@qq.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add e.xml
          git commit -m "Update e.xml"
          git push -f origin main
