name: rm old_epg

on:
  schedule:
    - cron: "10 17 * * *"   # 设置定时执行，例如每天零点执行
  workflow_dispatch:    # 允许手动执行
  
jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
          
      - name: Rm 10_days_ago epg
        run: |
          echo "${{ secrets.USERNAME }}"
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ github.actor }}"
          FILE="epg-$(date -d "10 days ago +8 hours" "+%m%d").xml"
          if [ -f "$FILE" ]; then
            git rm "$FILE"
            git commit -m "Remove $FILE"
            git push origin main
          else
            echo "File $FILE does not exist, skipping removal."
          fi
