name: rm old_epg

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 17 * * *"   # 设置定时执行，例如每天零点执行
  workflow_dispatch:    # 允许手动执行
  
jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
          
      - name: Rm 10_days_ago epg
        run: |
          echo "${{ secrets.USERNAME }}"
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ github.actor }}"
          git rm "epg-"$(date -d "10 days ago +8 hours" "+%m%d")".xml"
          git commit -m "Remove epg-$(date -d "10 days ago" "+%m%d").xml"
          git push origin main

      - name: checkin
        run: |
          time=$(($RANDOM%300));echo $time
          sleep $time
          response_1=$(curl -X POST --data "username=${{ secrets.USERNAME }}&password=${{ secrets.PASSWORD }}" "${{ secrets.URL_1 }}")
          ref_1=$(echo "$response_1" | grep -o "欢迎" | head -n 1)
          if [ "$ref_1" = "欢迎" ]; then
              echo "登录成功"
          else
              echo "登录失败"
          fi
          response_2=$(curl "${{ secrets.URL_2 }}")
          ref_2=$(echo "$response_2" | grep -oE "积分 [0-9]+, 距离下一级还需 [0-9]+ 积分")
          last_visit=$(echo "$response_2" | grep -oP '<li><em>最后访问</em>\K[^<]+' | sed 's/^\s*//;s/\s*$//')
          echo "最后访问时间: $last_visit  $ref_2"
