name: rm old_epg

on:
  schedule:
    - cron: "10 17 * * *"   # 设置定时执行，例如每天零点执行
  workflow_dispatch:    # 允许手动执行
  
jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
          
      - name: Rm 10_days_ago epg
        run: |
          echo "${{ secrets.USERNAME }}"
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ github.actor }}"
          FILE="epg-$(date -d "10 days ago +8 hours" "+%m%d").xml"
          if [ -f "$FILE" ]; then
            git rm "$FILE"
            git commit -m "Remove $FILE"
            git push origin main
          else
            echo "File $FILE does not exist, skipping removal."
          fi

      - name: checkin
        run: |
          # time=$(($RANDOM%120));echo $time
          # sleep $time
          response_1=$(curl -s -X POST --data "username=${{ secrets.USERNAME }}&password=${{ secrets.PASSWORD }}" "${{ secrets.URL_1 }}")
          ref_1=$(echo "$response_1" | grep -o "欢迎" | head -n 1)
          if [ "$ref_1" = "欢迎" ]; then
              echo "登录成功"
          else
              echo "登录失败"
          fi
          # time=$(( ($RANDOM % 60) + 120 ));echo $time
          # sleep $time
          # user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
          # data="typeid=3159&subject=打卡&file=&message=签到&formhash=cc56a04c&usesig=1&posttime=1704904044"
          # response_3=$(curl -X POST "${{ secrets.URL_3 }}" -H "User-Agent: $user_agent" -H "Cookie: ${{ secrets.COOKIE }}" --data "$data")
          # echo "$response_3"
          response_2=$(curl -s "${{ secrets.URL_2 }}")
          ref_2=$(echo "$response_2" | grep -oE "积分 [0-9]+, 距离下一级还需 [0-9]+ 积分")
          last_visit=$(echo "$response_2" | grep -oP '<li><em>最后访问</em>\K[^<]+' | sed 's/^\s*//;s/\s*$//')
          echo "最后访问时间: $last_visit  $ref_2"
          
