name: rm old_epg

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 15 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Rm 10_days_ago epg
        run: |
          git rm "epg-"$(date -d "10 days ago" "+%m%d")".xml"
          git commit -m "Remove epg-$(date -d "10 days ago" "+%m%d").xml"
          git push origin main
